//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductNum { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> MinNum { get; set; }
        public Nullable<int> MaxNum { get; set; }
        public Nullable<double> InPrice { get; set; }
        public Nullable<double> OutPrice { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public Nullable<int> StockNum { get; set; }
        public int PCateId { get; set; }
        public int MeasureId { get; set; }
        public int LocationId { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int IsDelete { get; set; }
        public string Remark { get; set; }
    }
}
